# Generated by Django 4.2.4 on 2023-08-18 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255)),
                ('ordering', models.IntegerField(default=0, verbose_name='Заказ')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='uploads/', verbose_name='Изображение')),
                ('thumbnail', models.ImageField(blank=True, upload_to='uploads/', verbose_name='Миниатюра')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category', verbose_name='Категория')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendor.vendor', verbose_name='Продавец')),
            ],
            options={
                'verbose_name_plural': 'Товары',
                'ordering': ['-date_added'],
            },
        ),
    ]
